---
- include_tasks: nginx-rhel.yaml
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"
  vars:
    __nginx_user: "nginx"
    __nginx_http_default_server_root: "/usr/share/nginx/html"

- include_tasks: nginx-debian.yaml
  when: ansible_distribution == "Ubuntu"
  vars:
    __nginx_user: "www-data"
    __nginx_http_default_server_root: "/var/www/html"
