---
- name: Make sure we have a 'wheel' group
  ansible.builtin.group:
    name: wheel
    state: present

- name: Allow 'wheel' group to have passwordless sudo
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Create a login user
  ansible.builtin.user:
    name: "{{ user }}"
    password: "{{ password | password_hash('sha512', salt) }}"
    groups:
      - wheel
    shell: /bin/bash
    state: present

- name: Set authorized keys
  ansible.builtin.authorized_key:
    user: "{{ user }}"
    state: present
    key: "{{ keys }}"
    exclusive: true
