---
- name: restart iptables
  become: true
  ansible.builtin.service:
    name: iptables
    enabled: true
    state: restarted
  when: 
    - not ansible_check_mode

- name: reload iptables
  become: true
  ansible.builtin.service:
    name: iptables
    enabled: true
    state: reloaded
  when: 
    - not ansible_check_mode
