---
- name: Install zabbix deb repo
  become: true
  ansible.builtin.apt:
    deb: "https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-1+ubuntu20.04_all.deb"
    state: present

- name: Install zabbix-agent
  become: true
  ansible.builtin.apt:
    update_cache: yes
    name: zabbix-agent
    state: present
  notify: restart zabbix-agent
