---
- name: Install zabbix rpm repo
  become: true
  ansible.builtin.dnf:
    name: 'https://repo.zabbix.com/zabbix/6.0/rhel/8/x86_64/zabbix-agent-6.0.3-1.el8.x86_64.rpm'
    state: present
    disable_gpg_check: true

- name: Install zabbix-agent
  become: true
  ansible.builtin.dnf:
    update_cache: yes
    name: zabbix-agent
    state: present
  notify: restart zabbix-agent
  when: not ansible_check_mode
