---
- include_tasks: dnf-zabbix-agent.yaml
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

- include_tasks: apt-zabbix-agent.yaml
  when: ansible_distribution == "Ubuntu"

- name: Zabbix-agent configs
  ansible.builtin.template:
    src: zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart zabbix-agent
