---
- name: Install MariaDB deb
  ansible.builtin.apt:
    update_cache: true
    name: mariadb-server
    state: present

- name: Add Python3 MardiaDB support deb
  ansible.builtin.apt:
    update_cache: true
    name: python3-pymysql
    state: present

- name: Start MardiaDB
  ansible.builtin.service:
    enabled: true
    name: mariadb
    state: started
  when:
    - not ansible_check_mode

- name: Set MardiaDB bind-address
  ansible.builtin.lineinfile:
    path: "/etc/mysql/mariadb.conf.d/50-server.cnf"
    regexp: '^(#)?\s*bind-address\s*='
    line: "bind-address={{ mysql_bind_address }}"
    state: present
  notify: 
    - restart mariadb

- import_tasks: mariadb-common.yaml
  vars:
    __mysql_unix_sock: "/run/mysqld/mysqld.sock"
  when: 
    - not ansible_check_mode


