---
- name: Install bash-completion package rpm
  ansible.builtin.dnf:
    update_cache: true
    name: bash-completion
    state: present

- name: Disable SELinux
  ansible.posix.selinux:
    configfile: "/etc/sysconfig/selinux"
    state: disabled
  tags: selinux
