---
- name: Disable UFW
  ansible.builtin.service:
    name: ufw
    enabled: false
    state: stopped

- name: Install iptables package deb
  ansible.builtin.apt:
    update_cache: true
    name: iptables
    state: present

- name: Install iptables-persistent package deb
  ansible.builtin.apt:
    update_cache: true
    name: iptables-persistent
    state: present

- name: Save old iptables rules
  community.general.iptables_state:
    path: "/etc/iptables/rules.v4"
    state: saved

- import_tasks: iptables-common.yaml

- name: Save new iptables rules 
  community.general.iptables_state:
    path: "/etc/iptables/rules.v4"
    state: saved

