---
# - name: Disable firewalld
#   ansible.builtin.service:
#     name: firewalld
#     enabled: false
#     state: stopped

- name: Install iptables package rpm
  ansible.builtin.dnf:
    update_cache: true
    name: iptables
    state: present
  notify: restart iptables

- name: Save old iptables rules
  community.general.iptables_state:
    path: "/etc/sysconfig/iptables"
    state: saved

- import_tasks: iptables-common.yaml

- name: Save new iptables rules 
  community.general.iptables_state:
    path: "/etc/sysconfig/iptables"
    state: saved
  notify: reload iptables
