---
- name: start nginx
  become: true
  ansible.builtin.service:
    enabled: true
    name: nginx
    state: started
  when:
    - not ansible_check_mode

- name: reload nginx
  become: true
  ansible.builtin.service:
    enabled: true
    name: nginx
    state: reloaded
  when:
    - not ansible_check_mode
